import type { LanguageCode } from './index';
import { ROBO_ENDGAME } from './roboEndgame';

const en = {
  controls: 'Foundry controls', blueprints: 'Blueprints', kernel: 'Kernel',
  blueprintHint: 'Spend RG to multiply production.', circuitHint: 'Grow four lines together for a factory-wide bonus.',
  firmwareHint: 'Choose how your factory works.', kernelHint: 'Restart your foundry. Keep permanent upgrades.',
  blueprintHelp: 'Local blueprints boost one line. Global blueprints boost every line. Both last until you Recompile.',
  circuitHelp: 'Own 10, 25, 50, then 100 robots in every line of a circuit. Each completed tier boosts ALL assembly lines automatically.',
  firmwareHelp: 'Choose one option per group. You pay once, and your choice stays locked until you Recompile. Read both options before installing.',
  kernelHelp: 'Recompile to turn lifetime production into Cores. Every Core earned permanently adds 10% passive production, even after you spend it on perks below.',
  batchHelp: 'RG in assembly is paid automatically when each batch finishes. The /s value is your average production.',
  chargeHelp: 'Own a line to charge automatically. A full battery gives 30 seconds of double passive production.',
  empty: 'No blueprints available yet. Grow your lines, or select All to see the unlock requirements.',
  buyMissing: 'Buy missing robots', sharedBonus: 'All-line circuit bonus', details: 'Line details',
  perRobot: 'Per robot /s', share: 'Factory share', cycle: 'Batch duration', lifetime: 'Lifetime output',
  nextEffect: 'After upgrade', currentEffect: 'Current effect',
};
type Guide = { [K in keyof typeof en]: string };
const translations: Record<Exclude<LanguageCode, 'en'>, readonly string[]> = {
  es: ['Controles de fundición','Planos','Núcleo','Gasta RG para multiplicar la producción.','Mejora cuatro líneas juntas para potenciar toda la fábrica.','Elige cómo funciona tu fábrica.','Reinicia la fundición. Conserva mejoras permanentes.','Los planos locales potencian una línea; los globales, todas. Duran hasta la recompilación.','Consigue 10, 25, 50 y 100 robots en cada línea del circuito. Cada nivel completado potencia TODAS las líneas automáticamente.','Elige una opción por grupo. Pagas una vez y queda bloqueada hasta recompilar. Lee ambas opciones antes de instalar.','Recompila para convertir la producción histórica en núcleos. Cada núcleo obtenido añade un 10% de producción pasiva permanente, incluso después de gastarlo en mejoras.','Los RG en montaje se cobran automáticamente al terminar cada lote. El valor /s es la producción media.','Posee una línea para cargar automáticamente. La batería llena duplica la producción pasiva durante 30 segundos.','Aún no hay planos disponibles. Mejora tus líneas o selecciona Todos para ver los requisitos.','Comprar robots faltantes','Bono de circuito para todas las líneas','Detalles de línea','Por robot /s','Porción de la fábrica','Duración del lote','Producción histórica','Tras mejorar','Efecto actual'],
  fr: ['Commandes de fonderie','Plans','Noyau','Dépensez des RG pour multiplier la production.','Développez quatre lignes pour améliorer toute la fabrique.','Choisissez le fonctionnement de votre fabrique.','Recommencez avec des améliorations permanentes.','Les plans locaux améliorent une ligne, les globaux toutes les lignes, jusqu’à la recompilation.','Possédez 10, 25, 50 puis 100 robots dans chaque ligne du circuit. Chaque palier améliore automatiquement TOUTES les lignes.','Une option par groupe, payée une fois et verrouillée jusqu’à la recompilation. Lisez les deux avant de choisir.','Recompilez pour convertir la production cumulée en cœurs. Chaque cœur gagné ajoute 10 % de production passive permanente, même après avoir été dépensé.','Les RG en assemblage sont versés automatiquement en fin de lot. /s indique la production moyenne.','Possédez une ligne pour charger automatiquement. Une batterie pleine double la production passive pendant 30 secondes.','Aucun plan disponible. Développez vos lignes ou sélectionnez Tous pour voir les conditions.','Acheter les robots manquants','Bonus de circuit de toutes les lignes','Détails de la ligne','Par robot /s','Part de la fabrique','Durée du lot','Production cumulée','Après amélioration','Effet actuel'],
  de: ['Gießereisteuerung','Baupläne','Kernel','RG ausgeben und Produktion vervielfachen.','Vier Linien gemeinsam ausbauen und die ganze Fabrik stärken.','Wähle, wie deine Fabrik arbeitet.','Gießerei neu starten. Dauerhafte Upgrades behalten.','Lokale Baupläne stärken eine Linie, globale alle Linien. Sie gelten bis zur Neukompilierung.','Besitze 10, 25, 50 und 100 Roboter in jeder Linie eines Schaltkreises. Jede Stufe stärkt automatisch ALLE Linien.','Eine Option pro Gruppe. Einmal bezahlen, bis zur Neukompilierung gebunden. Lies zuerst beide Optionen.','Kompiliere neu und wandle Gesamtproduktion in Kerne um. Jeder verdiente Kern gibt dauerhaft 10 % passive Produktion, auch nachdem du ihn ausgibst.','RG in Montage werden nach jeder Charge automatisch ausgezahlt. /s zeigt die durchschnittliche Produktion.','Besitze eine Linie zum automatischen Laden. Ein voller Akku verdoppelt die passive Produktion für 30 Sekunden.','Noch keine Baupläne verfügbar. Baue Linien aus oder wähle Alle für die Voraussetzungen.','Fehlende Roboter kaufen','Schaltkreisbonus für alle Linien','Liniendetails','Pro Roboter /s','Fabrikanteil','Chargendauer','Gesamtproduktion','Nach Upgrade','Aktueller Effekt'],
  zh: ['铸造厂控制','蓝图','内核','花费 RG，提高产量。','共同升级四条生产线，增强整个工厂。','选择工厂的工作方式。','重启铸造厂，保留永久升级。','局部蓝图增强一条生产线，全局蓝图增强所有生产线。持续至重新编译。','让回路内每条生产线分别拥有 10、25、50、100 个机器人。每完成一级，自动增强所有生产线。','每组选择一个选项。支付一次后锁定至重新编译。安装前请阅读两个选项。','重新编译，将历史产量转化为核心。每个已获得的核心永久增加 10% 被动产量，即使将其用于升级也不会失去加成。','每批完成时自动结算装配中的 RG。/s 表示平均产量。','拥有生产线即可自动充电。满电可让被动产量翻倍 30 秒。','暂无可用蓝图。升级生产线，或选择全部以查看解锁条件。','购买缺少的机器人','所有生产线的回路加成','生产线详情','每个机器人 /s','工厂产量占比','批次时长','历史产量','升级后','当前效果'],
  ar: ['التحكم بالمسبك','المخططات','النواة','أنفق RG لمضاعفة الإنتاج.','طوّر أربعة خطوط معاً لتعزيز المصنع كله.','اختر طريقة عمل مصنعك.','أعد تشغيل المسبك واحتفظ بالترقيات الدائمة.','المخططات المحلية تعزز خطاً واحداً والعالمية تعزز الجميع حتى إعادة التجميع.','امتلك 10 ثم 25 ثم 50 ثم 100 روبوت في كل خط بالدائرة. كل مستوى مكتمل يعزز جميع الخطوط تلقائياً.','اختر خياراً واحداً لكل مجموعة. تدفع مرة واحدة ويبقى الخيار مقفلاً حتى إعادة التجميع. اقرأ الخيارين قبل التثبيت.','أعد التجميع لتحويل الإنتاج التاريخي إلى أنوية. كل نواة مكتسبة تضيف 10٪ إنتاجاً سلبياً دائماً حتى بعد إنفاقها على الترقيات.','تُضاف RG قيد التجميع تلقائياً عند اكتمال كل دفعة. قيمة /s هي متوسط الإنتاج.','امتلك خطاً للشحن التلقائي. البطارية الممتلئة تضاعف الإنتاج السلبي لمدة 30 ثانية.','لا توجد مخططات متاحة بعد. طوّر خطوطك أو اختر الكل لعرض المتطلبات.','شراء الروبوتات الناقصة','مكافأة الدائرة لجميع الخطوط','تفاصيل الخط','لكل روبوت /s','حصة المصنع','مدة الدفعة','الإنتاج التاريخي','بعد الترقية','التأثير الحالي'],
  tr: ['Dökümhane kontrolleri','Planlar','Çekirdek','Üretimi katlamak için RG harca.','Dört hattı birlikte geliştir, tüm fabrikayı güçlendir.','Fabrikanın çalışma biçimini seç.','Dökümhaneyi yeniden başlat. Kalıcı yükseltmeleri koru.','Yerel planlar bir hattı, genel planlar tüm hatları güçlendirir. Yeniden derlemeye kadar sürer.','Devredeki her hatta sırasıyla 10, 25, 50 ve 100 robot bulundur. Her tamamlanan kademe TÜM hatları otomatik güçlendirir.','Her gruptan bir seçenek seç. Bir kez ödersin ve yeniden derlemeye kadar kilitlenir. Kurmadan önce iki seçeneği de oku.','Toplam üretimi çekirdeklere dönüştürmek için yeniden derle. Kazanılan her çekirdek, harcandıktan sonra bile kalıcı %10 pasif üretim ekler.','Montajdaki RG her parti bittiğinde otomatik ödenir. /s ortalama üretimdir.','Otomatik şarj için bir hatta sahip ol. Dolu pil 30 saniye boyunca pasif üretimi ikiye katlar.','Henüz kullanılabilir plan yok. Hatlarını geliştir veya gereksinimleri görmek için Tümü seç.','Eksik robotları satın al','Tüm hatların devre bonusu','Hat ayrıntıları','Robot başına /s','Fabrika payı','Parti süresi','Toplam üretim','Yükseltmeden sonra','Mevcut etki'],
};
const keys = Object.keys(en) as (keyof Guide)[];
export const ROBO_GUIDE: Record<LanguageCode, Guide> = {
  en, ...Object.fromEntries(Object.entries(translations).map(([language, values]) => [language,
    Object.fromEntries(keys.map((key, index) => [key, values[index]])),
  ])) as Record<Exclude<LanguageCode, 'en'>, Guide>,
};

for (const language of Object.keys(ROBO_GUIDE) as LanguageCode[]) {
  ROBO_GUIDE[language].kernelHelp = ROBO_ENDGAME[language].coreHelp;
  ROBO_GUIDE[language].circuitHelp = ROBO_ENDGAME[language].circuitHelp;
}
